print("Nume/prenume: Condorcahe Ștefan \n ")
print("data,anul:15.08.2004 \n" )
print("email:stefan.condorache@gmail.com \n ")
print("telefon:067****** \n ")
print("adresa:********** \n ")
print("studii:9 clase in scoala No I ''Mihai Eminescu''")
